development:
  dialect: mysql
  datasource: ${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST})/${DB_DATABASE}?tls=true&interpolateParams=true&parseTime=true
  dir: sql/migrations

# development:
#   dialect: mysql
#   datasource: root:mysql@tcp(127.0.0.1)/react_portfolio_dev?parseTime=true
#   dir: sql/migrations

# staging:
#   dialect: mysql
#   datasource: ${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST})/${DB_DATABASE}? 
#   charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
#   dir: sql/migrations
#   table: migrations
